version: 2
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn build
      - run: apt-get -y -qq update
      - run: apt-get -y -qq install python-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo easy_install pip
      - run: pip install awscli --upgrade --user
      - run: aws --version
      - run: aws s3 ls
      - run: yarn deploy
