version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ arch}}
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}-{{ arch}}

      - run: yarn lint

      - run: yarn size

      - run: yarn test

      - run: yarn build

      - aws-s3/sync:
          from: build
          to: "s3://kriss-react-cicd/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
